### ISSUE TITLE
Possible to use indexeddb?

### ISSUE THREAD

**Issue by SoroTrestal** [xanf/vuex-shared-mutations#10]
Hello is it possible to perhaps use indexeddb using localForage instead of localstorage? I have a large set of data that im mutating. Are there any plans to provide this option? 

Thank you

Kind regards

**Comment by jmealo** [comment]
I was wondering about this too. @SoroTrestal did you make any progress?

**Comment by SoroTrestal** [comment]
Sadly no, as a workaround i have implemented a global event bus on my window/opener object, i'm using golden layout where you can pop out any container into new window. The global event bus implementation works for now.

**Comment by xanf** [comment]
I believe it's bad idea. You can use SharedWorker if you need something global.

**Comment by SoroTrestal** [comment]
@xanf Ok, thanks for the info, but alltough you have closed the issue, do you have plans for implementing indexeddb using localForage instead of localstorage?

Thanks

**Comment by xanf** [comment]
@SoroTrestal unfortunately IndexedDB observers are available only in Chrome:
https://www.chromestatus.com/feature/5669292892749824
