### ISSUE TITLE
How to implement this vuex-shared-mutations with nuxtjs

### ISSUE THREAD

**Issue by folamy** [xanf/vuex-shared-mutations#14]
Please How can i used vuex-shared-mutations with nuxtjs

**Comment by folamy** [comment]
my code looks like
`//plugin/sharedmutations.js
import createMutationsSharer from 'vuex-shared-mutations';
import Vuex from 'vuex'

const store = new Vuex.Store({
  // ...
  plugins: [
    createMutationsSharer({
      predicate: (mutation, state) => {
        const predicate = ['addTocart', 'qtyInc', 'qtyDec', 'qtyReset']
        return predicate.indexOf(mutation.type) >= 0;
      },
    }),
  ],
});

//nuxt-config.js
//plugins
plugins: [
    '@/plugins/sharedMutation',
  ],

`

**Comment by HShao0130** [comment]
> my code looks like
> `//plugin/sharedmutations.js
> import createMutationsSharer from 'vuex-shared-mutations';
> import Vuex from 'vuex'
> 
> const store = new Vuex.Store({
> // ...
> plugins: [
> createMutationsSharer({
> predicate: (mutation, state) => {
> const predicate = ['addTocart', 'qtyInc', 'qtyDec', 'qtyReset']
> return predicate.indexOf(mutation.type) >= 0;
> },
> }),
> ],
> });
> 
> //nuxt-config.js
> //plugins
> plugins: [
> '@/plugins/sharedMutation',
> ],
> 
> `

can it work?I know a [vuex-persistedstate](https://github.com/robinvdvleuten/vuex-persistedstate) that it work in nuxt like:
`
// nuxt.config.js

...
plugins: [{ src: '~/plugins/localStorage.js', ssr: false }]
...
 `
`
// ~/plugins/localStorage.js

import createPersistedState from 'vuex-persistedstate'

export default ({store}) => {
  window.onNuxtReady(() => {
    createPersistedState({
        key: 'yourkey',
        paths: [...]
        ...
    })(store)
  })
}
`
But I don't know how to implement this one

**Comment by xanf** [comment]
I'll take a look on that in next 48h alongside with releasing new version

**Comment by wSedlacek** [comment]
@xanf Did you ever get a chance to look into this? This plugin looks super handy for my Nuxt project however I would like to use it as a Nuxt.js Plugin as @folamy was attempting to. An example of how to use it in this way would be fantastic!

**Comment by xanf** [comment]
I'm in process of full plugin rewrite, I expect to finish it this weekend
:)

**Comment by xanf** [comment]
@wSedlacek 
https://github.com/xanf/vuex-shared-mutations/tree/master/examples/nuxt

See v1.0.2 of this plugin
