### ISSUE TITLE
The state only get shared on mutation commits

### ISSUE THREAD

**Issue by MitsuhaKitsune** [xanf/vuex-shared-mutations#6]
When I try to create multiple instances of my store, the plugin work fine sharing the datas between it, but only when I commit a mutation all instances get updated.

If I don't commit a mutation the secondary storage instances still with default values instead take the states of first vuex instance.

Any way to sync states on init?

**Comment by justin-schroeder** [comment]
Just a passer by, but I think you're observing the intended behavior. Vuex stores should only have their data mutated via mutations. From the docs:

> The only way to actually change state in a Vuex store is by committing a mutation.

https://vuex.vuejs.org/en/mutations.html

**Comment by MitsuhaKitsune** [comment]
You can clone the current state with vuex api, finally I wrote a module to my needs, check https://github.com/MitsuhaKitsune/vuex-webextensions/blob/master/src/ui.js#L11, there I clone the all current state into the new store instance

https://vuex.vuejs.org/en/api.html replaceState method

**Comment by xanf** [comment]
@MitsuhaKitsune great your issue solved. This plugin is focused around "official" way of changing state via mutations. "replaceState" is intentionally not handled here (mostly because if you're building your app for web there are more efficient ways to do that - for example localStorage sync)
